version: "3"
services:
  camel-agent-uplink:
    # if something fails or the server is restarted, the container will restart
    restart: always 
    container_name: camel-agent-uplink
    image: camel-agent-uplink
    build: 
      # build the iris clasifier image from the Dockerfile in the current directory
      context: . 